### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by freyfrey01** [EvelynSubarrow/Albatross#2]
CommandSpy continuously gives a certificate warning. Tried changing settings in config.yml to not check for update but config gets reset every time server starts.
[latest.log](https://github.com/EvelynSubarrow/Albatross/files/5731602/latest.log)

**Comment by EvelynSubarrow** [comment]
Ah, this isn't strictly speaking a bug with the plugin itself, the problem is that the update file sits on albatross.evelyn.moe. and apparently certbot isn't quite getting nginx to reload config on that end. I've reloaded nginx for now, so it should work ok, and I'll give the configuration on the server end another look
