### ISSUE TITLE
Cannot remove commands from the ignore list

### ISSUE THREAD

**Issue by joycourier** [EvelynSubarrow/Albatross#4]
This plugin is fantastic. Downloaded it from SpigotMC and it works like a charm, configuration is great too.

However, I'm unable to figure out how to remove commands from the ignore list...

It should be /commandspy clear to clear them all, right? That doesn't do it
What about /commandspy ignore clear <user> <command>? That won't work either...

Is there a way to remove commands from the ignore list or is this just an oversight?

**Comment by EvelynSubarrow** [comment]
Thank you, it's good to hear that this plugin is useful!

Looking over, the lack of ability to remove something from the ignore list does seem to be an oversight on my part. If you don't have a long ignore list, in the meantime you might be able to just use the 'set' subcommand to replace the ignores with a single one. In any event, I'll add this capability!

**Comment by joycourier** [comment]
Thank you Evelyn, using "/commandspy ignore set @ *" worked, cleared every ignore but the command blocks.
I was trying "/commandspy set @ *" which explains why it wasn't working, haha. 

It may just be my incredibly smooth brain but the commands seem a little confusing, is there any documentation anywhere?

Also, is there a way to set an _exact_ string to ignore? For example:
If I do "/commandspy ignore add joycourier /r", it successfully hides my own replies from me, but it also hides _every_ other command that starts with 'r' like /region, /restart, /randomtp, etc.

**Comment by EvelynSubarrow** [comment]
The commands are somewhat documented on spigot (https://www.spigotmc.org/resources/commandspy.61494/), but that's really the best it gets. In general the oddness of its commands is down to the fact that it's an overcapable rules manager, the commands you use to interact with your personal cs settings are the exact same as you use to interact with the ignores, it's fundamentally the same code underneath, just accessed in a slightly different way.

As for it matching *anywhere* in the command, that's obviously not desirable, this is just because it matches the entire command string. You might be able to add a trailing space but I'm not sure on that point, I'm not sure whether more regex substitutions or a better way to build them might be necessary but I'll give this a think

**Comment by joycourier** [comment]
Hello Evelyn, only just got around to trying the "trailing space" idea, unfortunately that doesn't work, neither does wrapping the command in speechmarks or apostrophes :(

**Comment by EvelynSubarrow** [comment]
I'm so sorry, what with one thing and another I've been forgetting this issue. I'll try to dedicate some time to it soon

**Comment by EvelynSubarrow** [comment]
I've made the commit now, what this does is adds a 'clear' subcommand to groups, so you'll be able to use `/commandspy ignore clear`. I'll be putting this on Spigot first, I'll let you know when this is done!

**Comment by EvelynSubarrow** [comment]
It's now on spigot!
